# Generated by Django 6.1 on 2026-09-13 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("year", models.IntegerField(default=2026)),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma-separated technologies, e.g. Python, PyTorch, Gradio",
                        max_length=255,
                    ),
                ),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
