# Generated by Django 6.1 on 2026-09-27 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("campus", "Tingkat Kampus"),
                            ("national", "Tingkat Nasional"),
                            ("international", "Tingkat International"),
                        ],
                        default="campus",
                        max_length=20,
                    ),
                ),
                ("achieved_at", models.DateField()),
            ],
        ),
    ]
